### ISSUE TITLE
Add an option to pass custom task_id generation function to broker.

### ISSUE THREAD

**Issue by s3rius** [taskiq-python/taskiq#10]
Sometimes it might be useful to pass some task_id generation function. 

```python
def custom_generator(task: AsyncTaskiqDecoratedTask[_A, _B]) -> str
    return f"{task.original_function.__name__}"


@broker.task(id_generator=custom_generator)
def my_task():
    print("HEH")
```

This thing will be overriding results of an execution of this function. Or do you guys think it's useless? Because now we generate UUID for each task.

**Comment by s3rius** [comment]
@wbwswt, @chandr-andr ?

**Comment by chandr-andr** [comment]
Hm, nice idea. I think we can add it.
What's more, maybe we can create some base task_id generation functions or callable classes.
For example, task_id will be generated based on function name:

```
@broker.task(id_generator=id_based_on_task_name)
def my_shit_task():
    return("my awesome func!")
```

task_id will be `my_shit_task_<random_uuid>`. This will make it super easy to find the right logs for a specific task.

**Comment by s3rius** [comment]
LGTM. I'll try to make prototype this week.

**Comment by s3rius** [comment]
This function is added in #23.
