### ISSUE TITLE
Worker and startupt script

### ISSUE THREAD

**Issue by Emilianocm23** [taskiq-python/taskiq#106]
Hello , im trying to run some code at the startup of my script, in more detail, I need to open several browsers (playwright) for automated testing before listening for tasks. 

I run the worker and i see it's running my startup code 2 times, how can i prevent that? 
![Screenshot_6](https://user-images.githubusercontent.com/74161942/231528490-cfad01d3-2189-4133-b4fe-9eca48fb0fc8.png)

Right now, the way im doing it its by importing the module on my tasks file with the "browsers" list variable. But it's running twice and failing because of that

**Comment by s3rius** [comment]
Hi. That's because taskiq uses mutiprocesses to spawn multiple instances of workers. 

If you want to startup only one process, simply pass `--workers 1`.

**Comment by chandr-andr** [comment]
Hi! Thank you for your issue!
Could you, please, try to specify `--workers 1`?  
```
taskiq worker mycode:broker --workers 1
```

**Comment by s3rius** [comment]
@chandr-andr, thanks for your help.

**Comment by Emilianocm23** [comment]
Thank you, that worked perfectly @s3rius and @chandr-andr !


One question, can i run workers in multiple servers at the same time? let's say i have 3 different servers, same redis queue for all and i want to send tasks from my python website and execute that task on any free worker?

![option 2](https://user-images.githubusercontent.com/74161942/231534415-aa165ed5-ad8e-4dcf-92df-c718561e0503.png)

**Comment by s3rius** [comment]
Sure. That what taskiq is all about. It was designed to use it this way.
