### ISSUE TITLE
Startup & Shutdown events

### ISSUE THREAD

**Issue by Emilianocm23** [taskiq-python/taskiq#107]
hello, this is not an issue but i can't seem to find it inside your documentation.

How can i use Startup & Shutdown events?

Im currently using arq but i would like to migrate to taskiq 👍 

```
async def startup(ctx):
    from testing.browser import browsers
    ctx['browsers'] = browsers


async def stop_browsers(browser):
    browser.terminate()


async def shutdown(ctx):
    browsers = ctx.get('browsers')
    if browsers:
        tasks = []
        for browser in browsers:
            tasks.append(asyncio.ensure_future(stop_browsers(browser)))
        await asyncio.gather(*tasks)
```
This is how i currently use it on the other library, can you please link me to your docs on how to do it on taskiq?

Thanks for actively work on this library

**Comment by Emilianocm23** [comment]
Edit:

https://taskiq-python.github.io/guide/state-and-deps.html#state

Here is it, i just needed to use the search option in the docs. 

Sorry for this, will for sure integrate Taskiq into my project. 👍

**Comment by s3rius** [comment]
Thank you for raising this issue. Maybe it would be better to move this information to a separate section . 

If you're happy with taskiq, please leave a comment here, if you want: https://github.com/orgs/taskiq-python/discussions/69
