### ISSUE TITLE
NoneType error  while calling taskiq worker broker:broker  --reload -fsd --help

### ISSUE THREAD

**Issue by Kokoserver** [taskiq-python/taskiq#108]
when i try to run my task using  'taskiq worker fermerce.taskiq.broker:broker  --reload -fsd'
i keep getting this error:

  File "C:\Users\owoni\AppData\Local\pypoetry\Cache\virtualenvs\fermerce-b6doc62F-py3.11\Lib\site-packages\taskiq\cli\worker\process_manager.py", line 148, in __init__
    FileWatcher(
TypeError: 'NoneType' object is not callable

**Comment by s3rius** [comment]
Hi, @Kokoserver, can you try install `taskiq[reload]`? Now reload dependencies are not installed along with taskiq to reduce package for production. It's described in [HotReload section](https://taskiq-python.github.io/guide/cli.html#hot-reload) in docs.

I leave this issue open, until we create a PR that makes it obvious how to solve the issue.

**Comment by Kokoserver** [comment]
oh i see thank you @s3rius
