### ISSUE TITLE
Task schedulers do not work

### ISSUE THREAD

**Issue by geofferyj** [taskiq-python/taskiq#142]

**Comment by s3rius** [comment]
Can you provide more information about your problem?

**Comment by geofferyj** [comment]
I followed the example on the doc for setting up the scheduler, but I didn't see any logs saying the scheduler was working

I had initially tested with a single task but I need to run a task every 10 seconds

**Comment by s3rius** [comment]
It seems that your worker cannot resolve tasks. Do you have any integration with frameworks like taskiq-fastapi? 

If so, I guess, I found the problem. Will fix it soon.

**Comment by geofferyj** [comment]
Yes I am using fastapi.

I'll wait for the fix.

**Comment by s3rius** [comment]
So, here's a catch about schedulers. It works on tasks it can discover. I guess your scheduler just cannot find tasks that your scheduled.

There are several ways to fix it:
1. Use --fs-discover with task-file patterns.
2. Import it somewhere in your main broker's file. 

The fix to integration is going to import application when starting up scheduler, so it's going to discover all tasks that are used in your web-application. If you have a task that exists in some different file, I guess you would still need to use one of two mentioned solutions.

**Comment by s3rius** [comment]
I hope it helped.

If you find your experience with [taskiq](https://github.com/taskiq-python/taskiq) pleasant, you can help us improve, by hitting the star button, giving us feedback here in the [discussion](https://github.com/orgs/taskiq-python/discussions/69) or becoming a [sponsor](https://github.com/sponsors/taskiq-python) (Github will give you a cool sponsor emblem on your profile).
