### ISSUE TITLE
Dependencies close parameter error, exception handling

### ISSUE THREAD

**Issue by Kitefiko** [taskiq-python/taskiq#146]
Hello,
there is a error during closing of dependencies here: 
https://github.com/taskiq-python/taskiq/blob/3f8af4563128b5597d797d0dd29dee2863a74236/taskiq/receiver/receiver.py#L232-L240

caused by `AsyncResolveContext.close` not accepting arguments.

I also suspect this is at least partially the reason why [Exception handling via generator](https://taskiq-python.github.io/guide/state-and-deps.html#exception-handling) is not working?

**Comment by s3rius** [comment]
Hi and thanks for raising this issue. I'm pretty sure that it works. Since we have tests for that.

Can you please try updating taskiq-dependencies package?

**Comment by Kitefiko** [comment]
You are absolutely correct, updating `taskiq-dependencies` fixes the issue. It seems that since `taskiq` has `taskiq-dependencies` as dependency set to ["^1"](https://github.com/taskiq-python/taskiq/blob/3f8af4563128b5597d797d0dd29dee2863a74236/pyproject.toml#LL34C15-L34C15), poetry was happy with using version 1.0.0. 
Might be good idea to increase the version?

Thank you for quick reply and help :)

**Comment by s3rius** [comment]
Yes. I guess you right. It will be fixed in subsequent releases.
