### ISSUE TITLE
Feature: SQS Broker

### ISSUE THREAD

**Issue by fubuloubu** [taskiq-python/taskiq#149]
I couldn't find any plugin/extension for an AWS SQS Broker for TaskIQ, so I was thinking of creating one. Any feedback or suggestions?

**Comment by s3rius** [comment]
Hello and thanks for raising this issue. I was thinking about it for a while, but didn't implemented it. You can take a look at different brokers and how they implemented and there's a small [template](https://taskiq-python.github.io/extending-taskiq/broker.html) for brokers.

For initial project creation, you can use https://github.com/taskiq-python/project-template.

You can ask me about anything related to this task:
* [My telegram](https://t.me/s3rius_san)
* My discord: `s3rius#8298`

**Comment by fubuloubu** [comment]
Thank you! Will do

**Comment by MuriloScarpaSitonio** [comment]
Hello!

Has the development of this broker advanced? If yes, I would like to help. If not, I would like to know because I will start one from scratch. 

Thanks in advance!

**Comment by Kokoserver** [comment]
hello everyone, i'm trying to do something similar i just want to know if it has been done. @fubuloubu

**Comment by fubuloubu** [comment]
> hello everyone, i'm trying to do something similar i just want to know if it has been done. @fubuloubu

No, never ended up making one, but if you do and open source it, please link it here

**Comment by Kokoserver** [comment]
Thanks for a quick response, it will be nice to support that in the main project just as we have redis, rabbitmq.

**Comment by s3rius** [comment]
Okay, will do it this weekend.

**Comment by Kokoserver** [comment]
i will be waiting for the update

**Comment by Kokoserver** [comment]
thanks

**Comment by fubuloubu** [comment]
We ended up making one and open sourcing it (h/t @mikeshultz)

Not production material, just fit our use case and wanted to open source it
https://github.com/ApeWorX/taskiq-sqs

Happy to combine with your work @s3rius

**Comment by fubuloubu** [comment]
btw, we have started testing w/ https://github.com/ApeWorX/taskiq-sqs and it is working well. I hope some folks out there will give it a shot!

**Comment by fubuloubu** [comment]
@s3rius if you would like, we can donate the package over to you. We are no longer maintaining it

**Comment by danfimov** [comment]
Good idea. I will need SQS broker for my current work project and can maintain package if needed

**Comment by fubuloubu** [comment]
> Good idea. I will need SQS broker for my current work project and can maintain package if needed

I initiated the transfer to you, and I think you can move it to taskiq-python.

Let me know your pypi name and I can add you

**Comment by danfimov** [comment]
Already transferred to org, thank you, @fubuloubu : https://github.com/taskiq-python/taskiq-sqs 

I think it would be a good idea to add `taskiq-python` as a PyPI package owner so it isn’t tied to me personally (if it's possible to do): https://pypi.org/org/taskiq/

**Comment by fubuloubu** [comment]
I added your personal account as a maintainer on pypi, it does not let me add an organization directly. Please confirm once accepted

> I think it would be a good idea to add `taskiq-python` as a PyPI package owner so it isn’t tied to me personally (if it's possible to do): https://pypi.org/org/taskiq/

You can only transfer ownership to orgs that you are an owner of, I removed it from our ownership (which accidentally removed me as an owner as well) so we will need to see if @mikeshultz can make you an owner so that you can migrate it over to the taskiq organization. You might need to be an owner of that org for that to be done.

**Comment by danfimov** [comment]
I accepted an invitation, all good. Will wait for Mike because now as a maintainer I can't even configure new trusted publisher
