### ISSUE TITLE
Logging configuration should not impact loggers outside `taskiq`

### ISSUE THREAD

**Issue by MuriloScarpaSitonio** [taskiq-python/taskiq#158]
My team uses Datadog (DD) for monitoring and we deploy using containers with default configuration - which means that everything emitted to `stdout`/`stderr` is pushed to DD as log.

The worker cli entrypoint (`taskiq.cli.worker.run.run_worker`) currently defines logging configuration using `logging.basicConfig` and I think this should be avoided because doing so configures the root logger (`logging.root`), impacting all other loggers in the hierarchy.

In my use case, I have a logger with a custom formatter to emit logs in a format thad DD can parse. As `taskiq` is using `logging.basicConfig` this adds a handler to the root logger then all logs emitted by my logger are also being emitted by the root handler (`StreamHandler`). This is causing duplicates in DD and, on top of that, the logs emitted by the root handler are being marked with `ERROR` regardless the actual log level because this handler uses `sys.stderr` as a stream.

My suggestion: get rid of `logging.basicConfig` and define a root log for `taskiq` instead of applying rules to root logger of the whole application - i.e. do something like this instead:

```python
logger = logging.getLogger("taskiq")
handler = logging.StreamHandler(stream=sys.stdout)
handler.setFormatter(logging.Formatter(args.log_collector_format))
logger.setLevel(logging.getLevelName(args.log_level))
``` 

For the record, my current solution was to not propagate logs emitted by my custom handler...
```python
logger = logging.getLogger("my_cutom_logger")
logger.propagate = False
...
``` 
... and regarding the `sys.stderr` thing, I'm currently running the worker with `--log-level=${TASKIQ_LOG_LEVEL:-ERROR}` so no big deal (although I wouldn't know how to easily adjust this if I was using a lower value for `--log-level`).

**Comment by s3rius** [comment]
Hi, and thanks for raising this issue! Looks really reasonable, and as I know, many people use super custom log formats. 

I guess it's a good idea to get rid of this. Will try to do something with it. Or, alternatively you can try submitting a PR that works in exactly your case.

**Comment by s3rius** [comment]
@MuriloScarpaSitonio, please take a look at #159. If it works for you, we're going to release new version right after your approve.

**Comment by MuriloScarpaSitonio** [comment]
Thanks, @s3rius! I just left a comment there. Unfortunately, I don't have much time this week otherwise I could try to push a PR. Next week will be more relaxed for me, so if it's ok for you I think I can work on a PR.
