### ISSUE TITLE
How to use taskiq without global variables?

### ISSUE THREAD

**Issue by cofob** [taskiq-python/taskiq#178]
Hello!

I found your project very useful and it fits as a replacement for synchronous celery, but unfortunately I didn't find in the documentation a description of the way to run taskiq without global variables.

Here is an example with global variables:
```python
from taskiq import InMemoryBroker

broker = InMemoryBroker()

@broker.task
async def some_task():
    pass
```

I made a small [wrapper class](https://gist.github.com/cofob/70ac670c8917bd3b727ec2107aed0e2c) above `AsyncBroker` and `AsyncTaskiqDecoratedTask` that act like `fastapi.Router` to avoid creating a global broker and allow its replacement on already initialized tasks ([usage example](https://gist.github.com/cofob/4c2eb2b3dcb61571a50b2f746a07cf1e)).

I would like to know if there are any in-house tools to create something like this in taskiq, and if not, is it planned?

Also, it would be nice to have a `--factory` option in the `taskiq worker` command, like in [uvicorn](https://www.uvicorn.org/#command-line-options), to solve this problem. That is, so that startup can be done as `taskiq worker --factory project.tasks:broker_factory` and combined with TaskGroup.

`project/tasks.py`:
```python
from taskiq import InMemoryBroker, AsyncBroker
from .image_tasks import group as image_group

async def broker_factory() -> AsyncBroker:
    broker = InMemoryBroker()
    image_group.setup_broker(broker)
    await broker.startup()
    return broker
```

I am willing to help with the implementation of this functionality if there is a need for it.
Thank you in advance for your answer!

**Comment by s3rius** [comment]
Hi and thanks for raising this issue. Ca you please provide an example how non-global broker can be used? Because currently I don't see a possible usecase for such scenario. 

Factory method is not a bad idea, but it would be hard to define tasks this way. You already can define tasks that are not bound to a specific broker using [async_shared_broker](https://taskiq-python.github.io/available-components/brokers.html#async-shared-broker-and-shared-tasks).

**Comment by s3rius** [comment]
So, here's how you can do the same thing you did in the example.

```python
import asyncio
from asyncio import sleep

from taskiq import InMemoryBroker, async_shared_broker


class AwaitableBroker(InMemoryBroker):
    async def wait_all(self) -> None:
        for task in list(self._running_tasks):
            await task


@async_shared_broker.task()
async def test_task(s: int) -> None:
    await sleep(s)
    print("Hello World")


async def main():
    broker = AwaitableBroker()

    await broker.startup()

    await test_task.kicker().with_broker(broker).kiq(1)
    await test_task.kicker().with_broker(broker).kiq(2)
    await test_task.kicker().with_broker(broker).kiq(3)
    await test_task.kicker().with_broker(broker).kiq(4)

    await broker.wait_all()

    await broker.shutdown()


if __name__ == "__main__":
    asyncio.run(main())

```

It does literally the same thing. But I await for all tasks to complete at the end. In order to add such function, I created a broker that can wait for all tasks to complete.

**Comment by cofob** [comment]
> Can you please provide an example how non-global broker can be used? Because currently I don't see a possible usecase for such scenario.

The usage is exactly the same as a normal broker, just without declaring a global variable and increasing the flexibility of the library. I agree that it's a bit more complicated, but it's still better to have both on hand. For example with task group I can have several different types of wokers with common tasks.

Also thanks for the `async_shared_broker` example, I'd rather use the standard library tools without major modifications.

**Comment by cofob** [comment]
Close?

**Comment by s3rius** [comment]
If you fully agree that issue can be considered as closed, please close it.
