### ISSUE TITLE
How to run task later

### ISSUE THREAD

**Issue by toxazhl** [taskiq-python/taskiq#185]
I found about the schedule in the documentation, but I did not find how to create a deferred task that will run once

**Comment by s3rius** [comment]
Hi! It's not at docs yet, but you can use `time` parameter instead of cron.

**Comment by toxazhl** [comment]
Yes, thank you

**Comment by s3rius** [comment]
@toxazhl, hi. Regarding your question. Maybe this gist will be useful for you: https://gist.github.com/s3rius/f54301d28fe34159f24b7bb9c0d51939.
