### ISSUE TITLE
Run workers and schedulers programmatically

### ISSUE THREAD

**Issue by igoose1** [taskiq-python/taskiq#192]
Worker and scheduler had been written to be cli-first. I suggest to move all logic to Worker/Scheduler classes and make [cli module](https://github.com/taskiq-python/taskiq/tree/master/taskiq/cli) just an interface to them.

Currently, to launch taskiq workers I should provide `WorkerArgs` to `run_worker`. It's a huge class without default values because it's hard-coded to be used with `argparse`.

### Example
I want to show how [uvicorn](https://www.uvicorn.org/) (ASGI web server implementation) works. Server can be launched from a command line:

```sh
$ uvicorn main:app
```

There's a code equivalent:

```python
import uvicorn

async def app(scope, receive, send):
    ...

if __name__ == "__main__":
    uvicorn.run("main:app", port=5000, log_level="info")
```

**Comment by s3rius** [comment]
It makes sense. Will try to add it later.

**Comment by dtatarkin** [comment]
I faced the same problem and solved it by extracting peace of code from Taskiq to separate function

```
from concurrent.futures import ThreadPoolExecutor

from taskiq import AsyncBroker
from taskiq.cli.worker.run import shutdown_broker
from taskiq.receiver import Receiver


async def run_worker(broker: AsyncBroker, worker_params: TaskiqWorkerParams):
    try:
        with ThreadPoolExecutor(max_workers=worker_params.max_sync_workers) as pool:
            receiver = Receiver(
                broker=broker,
                executor=pool,
                validate_params=True,
                max_async_tasks=worker_params.max_async_tasks,
                max_prefetch=worker_params.max_prefetch,
            )
            broker.is_worker_process = True
            await receiver.listen()
    finally:
        await shutdown_broker(broker, worker_params.shutdown_timeout)
```

**Comment by s3rius** [comment]
Now we have a nice API for dynamic environments and now you can run brokers and schedulers right inside your application. 

However it was not possible to implement exactly the same functionality. If you want to run exactly the same functionality as in `taskiq worker`. You can do something like that.

```python
from taskiq_redis import ListQueueBroker

from taskiq.cli.worker.args import WorkerArgs
from taskiq.cli.worker.run import run_worker

broker = ListQueueBroker("redis://localhost")


def main():
    run_worker(WorkerArgs(broker="b:broker", modules=[], fs_discover=True))


if __name__ == "__main__":
    main()
``` 

But it's exactly the same and will completely block the main function.
