### ISSUE TITLE
Annotated dependencies not supported?

### ISSUE THREAD

**Issue by quizmoon** [taskiq-python/taskiq#197]
When I try to use annotated dependencies as described here:
https://fastapi.tiangolo.com/tutorial/dependencies/?h=annotated#share-annotated-dependencies

I get "missing required positional argument" error in the worker process.

Does annotated dependencies are supported or problem is somewhere on my side?

Thank you.

**Comment by s3rius** [comment]
Hi, @quizmoon, now `Annotated` dependencies are supported by taskiq. 

Please update `taskiq-dependencies` to https://github.com/taskiq-python/taskiq-dependencies/releases/tag/1.4.0.

**Comment by devraj** [comment]
@s3rius you do good work Sir.

**Comment by quizmoon** [comment]
Tested, working well. Thank you!
