### ISSUE TITLE
Bug: [Windows] Taskiq cannot find module

### ISSUE THREAD

**Issue by wbwswt** [taskiq-python/taskiq#20]
On a fresh installation, the library does not work as expected.
Steps to reproduce:
1. Create fresh project via `poetry init`
2. Create module and files
```
│   poetry.lock
│   pyproject.toml
│   __init__.py
│
└───tiq
        broker.py
        tasks.py
        __init__.py
```
3. Install taskiq `poetry add git+https://github.com/taskiq-python`
4. Trying to run `poetry run taskiq tiq.broker:broker1`

Get:
```
ModuleNotFoundError: No module named 'tiq'
ModuleNotFoundError: No module named 'tiq'
[2022-08-05 15:30:31,805][INFO   ][MainProce
```
```
poetry env info

Virtualenv
Python:         3.10.5
Implementation: CPython
Path:           C:\Users\gans\AppData\Local\pypoetry\Cache\virtualenvs\tiq-mVOzOutL-py3.10
Valid:          True

System
Platform: win32
OS:       nt
Python:   C:\Users\gans\AppData\Local\Programs\Python\Python310
```
I use official Python from python.org
OS Name:                   Microsoft Windows 10 Home Single Language
OS Version:                10.0.19044 N/A Build 19044

**Comment by s3rius** [comment]
Consider creating project with `poetry new` instead of `poetry init`. It may solve the problem.

**Comment by s3rius** [comment]
This bug's root cause is that you have a weird project structure and poetry cannot install it.

**Comment by s3rius** [comment]
Linked request fixes windows signal handlers.
