### ISSUE TITLE
What about integration with LiteStar?

### ISSUE THREAD

**Issue by pikhovkin** [taskiq-python/taskiq#216]
What about integration with [LiteStar](https://litestar.dev/)?

**Comment by s3rius** [comment]
It should be relatively easy to setup. Will add it.

**Comment by s3rius** [comment]
Hi. The integraton is ready. It doesn't support litestar way of dependency injection. But now you'll be able to access the state from within a tasks.

**Comment by s3rius** [comment]
Also, a small note on this project. Hence we provide a Litestar as an injectable, python fails to resolve it. I'm not sure why is it happening. Will fix it in https://github.com/taskiq-python/taskiq-dependencies.

**Comment by s3rius** [comment]
Closed as completed.
