### ISSUE TITLE
Matrix [protocol] broker

### ISSUE THREAD

**Issue by thebalaa** [taskiq-python/taskiq#241]
Hello TaskIQ,

As long time celery users we love this project and have been slowly migrating our systems to TaskIQ.

As part of transition journey we have built a Broker powered by the Matrix protocol.

https://github.com/fractalnetworksco/taskiq-matrix

This library is under active development and should be considered alpha quality. Also please note we have not validated its behavior in a federated context. This means that for now all workers are expected to be connected to the same Matrix homeserver.

We have tested with Synapse 1.95.1 and have seen good results.

Thank you for the wonderful project.

**Comment by s3rius** [comment]
Thank you for such a big contribution to the taskiq-ecosystem. And thanks for all warm words.
