### ISSUE TITLE
Dependency injection using `Annotated` fails with `from __future__ import annotations`

### ISSUE THREAD

**Issue by itssimon** [taskiq-python/taskiq#265]
When using the `Annotated` syntax for Taskiq dependencies and having the `from __future__ import annotations` import at the top of the file, dependency injection doesn't work. An error like below will be thrown:

```
TypeError: my_task() missing 1 required positional argument: 'my_dep'
```

I can imagine that this may be expected, so I'd suggest adding a note in the documentation so people don't waste as much time debugging this like I just did :)

Otherwise, maybe there is a clue in FastAPI on how to make it work even with the import from `__future__`?

**Comment by s3rius** [comment]
Since the algorithm we implemented in the [taskiq-dependencies](https://github.com/taskiq-python/taskiq-dependencies) is completely different to fastapi's DI, there would be no hints for fixing it. But I will debug this issue.

**Comment by s3rius** [comment]
Hi. I tried to reproduce the issue and everything seems to be fine. Even with annotation enabled. Here's how I tested it. 

```python
from __future__ import annotations
from taskiq_dependencies import Depends, DependencyGraph


def f() -> int:
    return 1


def g(f: int = Depends(f)) -> int:
    pass

with DependencyGraph(g).sync_ctx() as ctx:
    print(ctx.resolve_kwargs())
```

And here's an async variant (which also works).

```python
from __future__ import annotations
from taskiq_dependencies import Depends, DependencyGraph


async def f() -> int:
    return 1


async def g(f: int = Depends(f)) -> int:
    pass

async def meme() -> int:
    async with DependencyGraph(g).async_ctx() as ctx:
        print(await ctx.resolve_kwargs())

if __name__ == "__main__":
    import asyncio
    asyncio.run(meme())
```

Maybe this caused by specific version of python or TaskiqDepends. Can you check on which versions it fails?

**Comment by s3rius** [comment]
Now everything should work fine with `from __future__ import annotations` for python versions >= 3.10.

If that works for you, consider closing the issue.

**Comment by itssimon** [comment]
That works. Thank you!
