### ISSUE TITLE
Update watchmedo dependency version

### ISSUE THREAD

**Issue by mmzeynalli** [taskiq-python/taskiq#351]
`taskiq[reload] (0.11.7) depends on watchdog (>=2.1.9,<3.0.0)`.

Watchmedo right now has version of 4.0.2.

**Comment by s3rius** [comment]
Will update soon.

**Comment by s3rius** [comment]
Was updated in #354. Will be released soon.

**Comment by albireox** [comment]
Would it be possible to release this soon? This seems to break the build in macOS Sequoia.
