### ISSUE TITLE
Old version of importlib_metadata incompatible with other packages like specfs

### ISSUE THREAD

**Issue by lembregtse** [taskiq-python/taskiq#78]
Hi, great work here on this module. I have a small request, is it possible to upgrade the importlib_metadata package to a version > 4.3? Or is there a specific reason for the < 4.3 requirement?

Currently we are running into compatibility issues with s3fs / specfs due to this.

**Comment by s3rius** [comment]
Sure. I'll take a look. I don't remember, why we have such constraint.
