### ISSUE TITLE
testing taskiq

### ISSUE THREAD

**Issue by Kokoserver** [taskiq-python/taskiq#82]
I tried to surf the documentation could not fing a way to test taskiq, perhaps one or example should be provoded in the documentations

**Comment by s3rius** [comment]
Hi and thanks for raising this issue. Yes, maybe you're right. I'll add a section in docs later.


## Testing functions that execute tasks

Now I may suggest you just to add check that you're running in code in pytest.

```python
import os
from taskiq_redis import ListQueueBroker
from taskiq import InMemoryBroker

env = os.environ.get("ENVIRONMENT")

broker = ListQueueBroker("redis://localhost")

if env and env == "pytest":
    broker = InMemoryBroker()

```

Here I check that current ENVIRONMENT is pytest. Pytest itself doesn't add such variables, so you must add it by yourself before running tests. Like this:

```bash
export ENVIRONMENT="pytest"
pytest -vv
```

Or we can you [pytest-env](https://pypi.org/project/pytest-env/) to set ENV variables automatically before running tests.

```ini
# pytest.ini
[pytest]
env =
    ENVIRONMENT=pytest
``` 

This way you don't need to actually send tasks, and it will be executed almost as a normal functions. 

## Testing tasks

Tasks can be called as a normal function without kicking. So you can just call it. 

```python
# tasks.py file
@broker.task
async def my_task(val: str) -> int:
	return int(val)

...

# test_tasks.py file
async def test_task():
	res = my_task("11")
    assert res == 11
```


## Dependency injection

If you want to test functions that call taskiq tasks that depend on something, just add mocked base dependencies in your broker. You can add your base dependencies as a custom dependency_context.

For example, if you have a task, that depend on something, like Path (just for example).

```python
from {your_project}.taskiq import broker
from pathlib import Path
from taskiq import TaskiqDepends

@broker.task
async def my_task(val: str, some_path: Path = TaskiqDepends()):
    print(some_path)
    return int(val)
```

You could add this in your conftest.py

```python

@pytest.fixture(scope="function", autouse=True)
async def init_dependencies():
    broker.add_dependency_context({
        Path: Path.cwd()
    })
    
    yield

    broker.custom_dependency_context = {}

```

And if somewhere in your test some task is called, path will be resolved to the one we added in fixture. 

If you want to test task itself, just provide dependant variable as normal variable. Let's assume, we have a task as the above.


```python
import pathlib
import pytest
from {your_project}.tasks import my_task

@pytest.mark.anyio
async def test_my_func():
    res = await my_task("11", pathlib.Path().cwd())
    assert res == 11
 
```

**Comment by s3rius** [comment]
Leaving this issue open, until I add testing section in documentation.

**Comment by s3rius** [comment]
Hi, @Kokoserver, now we have a documentation for testing on our website. If your problem is solved, please consider closing this issue. 

Link to docs: https://taskiq-python.github.io/guide/testing-taskiq.html

**Comment by Kokoserver** [comment]
I can see that the documentation has been updated, i can close this issues now
