### ISSUE TITLE
Use semaphore to replace the current

### ISSUE THREAD

**Issue by vvanglro** [taskiq-python/taskiq#91]
https://github.com/taskiq-python/taskiq/blob/318b25b40e2cc9753c6e4c76b462a9627ecb0b62/taskiq/cli/worker/async_task_runner.py#L47-L49
We can use `asyncio.Semaphore` to replace the current scheme, and it is not recommended to set `max_async_tasks` less than 1, the infinite number of tasks will only cause unexpected situations.
Use `asyncio.Semaphore` to limit the number of tasks, assign task scheduling to the event loop, and avoid using `asyncio.wait` to increase power consumption concurrently.

**Comment by s3rius** [comment]
That's a really good suggestion. We will do it.

**Comment by vvanglro** [comment]
I can do PR if you want.

**Comment by s3rius** [comment]
That would be great.

**Comment by s3rius** [comment]
Thank you for your contribution. This issue will be closed automatically on next release.

**Comment by s3rius** [comment]
Released in https://github.com/taskiq-python/taskiq/releases/tag/0.4.0.
