### ISSUE TITLE
Reloading related dependencies should be optional

### ISSUE THREAD

**Issue by scabala** [taskiq-python/taskiq#95]
Hello,
I've seen that there's auto reload option for taskiq. It is pretty useful in development.  
In production installation, it is not needed most of the time but dependencies for it are installed regardless. And looking through the code, even if one will hack to install taskiq without i.e. `watchdog`, it will fail on imports.

**Comment by s3rius** [comment]
That's a good point. Thanks for that issue. I guess, we need to make these dependencies optional.

**Comment by s3rius** [comment]
Released in https://github.com/taskiq-python/taskiq/releases/tag/0.4.0.
