### ISSUE TITLE
Worker metrics

### ISSUE THREAD

**Issue by scabala** [taskiq-python/taskiq#96]
Dramatiq has built-in middleware that exposes worker metrics in Prometheus format: [here](https://github.com/Bogdanp/dramatiq/blob/master/dramatiq/middleware/prometheus.py).

Is it in scope for this project to provide something similar or should it be concern of users of taskiq? If the former, it would be good to allow users to attach custom metrics easily.

**Comment by s3rius** [comment]
Hi, and thanks for raising this issue. It's a good point and it would be nice to have metrics for workers. 

But still, it's super easy to add it yourself, untill we implement it.

Here's how you do it. 

1. Define metrics you want to see somewhere in your project. Using python [prometheus-client](https://github.com/prometheus/client_python) package.
```python
from prometheus_client import Counter

received_messages = Counter('received_messages', 'Number of received messages', ['task_name'])
success_tasks= Counter('sucess_tasks', 'Number of sucessfully executed tasks', ['task_name'])
found_errors= Counter('found_errors', 'Number of errors while executing tasks', ['task_name'])

```

2. To capture metrics, just create a middleware.

```python
from taskiq import TaskiqMiddleware

from your_project.metrics import received_tasks, success_tasks, found_errors

class PrometheusMiddleware(TaskiqMiddleware):  # pragma: no cover
    def pre_execute(
        self,
        message: "TaskiqMessage",
    ) -> "Union[TaskiqMessage, Coroutine[Any, Any, TaskiqMessage]]":
        received_tasks.labels(message.task_name).inc()

    def post_execute(
        self,
        message: "TaskiqMessage",
        result: "TaskiqResult[Any]",
    ) -> "Union[None, Coroutine[Any, Any, None]]":
        success_tasks.labels(message.task_name).inc()

    def on_error(
        self,
        message: "TaskiqMessage",
        result: "TaskiqResult[Any]",
        exception: Exception,
    ) -> "Union[None, Coroutine[Any, Any, None]]":
        found_errors.labels(message.task_name).inc()
```

3. Add your middleware to the broker and start prometheus server on startup.

```python
from taskiq import TaskiqEvents, TaskiqState
from prometheus_client import start_http_server
from your_project.taskiq_middleware import PrometheusMiddleware

broker = RandomBroker()

my_super_broker.add_middlewares(
    [
        PrometheusMiddleware(),
    ]
)

@broker.on_event(TaskiqEvents.WORKER_STARTUP)
async def add_metrics(_: TaskiqState):
    start_http_server(8000)
```

And please don't forget to set `PROMETHEUS_MULTIPROC_DIR` env variable for prometheus as it said in [docs](https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn). Maybe you can set it in startup event using os.environ.

**Comment by s3rius** [comment]
Prometheus middleware added in https://github.com/taskiq-python/taskiq/releases/tag/0.4.0.
